#ifndef ENUM_H
#define ENUM_H


enum UI_COLOUR {
    COLOUR_NONE,
    COLOUR_SOME,
    COLOUR_MANY
};


#define NUM_UI_PANELS 3
enum UI_PANEL {
   PANEL_SPLASH,
   PANEL_TERRAIN,
   PANEL_DETAIL
};


enum INPUT_MODE {
    INPUT_MODE_NONE,
    INPUT_MODE_CAPTURE,
    INPUT_MODE_NAVIGATE,
    INPUT_MODE_TERRAIN,
    INPUT_MODE_COMMAND
};


#define NUM_TERRAIN 9
enum TERRAIN {
    TERRAIN_NONE,
    TERRAIN_UNKNOWN,
    TERRAIN_WATER,
    TERRAIN_MOUNTAINS,
    TERRAIN_PLAINS,
    TERRAIN_HILLS,
    TERRAIN_FOREST,
    TERRAIN_DESERT,
    TERRAIN_JUNGLE,
    TERRAIN_SWAMP,
    TERRAIN_TUNDRA
};


#define NUM_DIRECTIONS 6
enum DIRECTION {
    EAST,
    NORTHEAST,
    NORTHWEST,
    WEST,
    SOUTHWEST,
    SOUTHEAST,
    DIRECTION_NONE
};

enum KEY {
    KEY_NONE,
    KEY_NEWLINE,
    KEY_ESCAPE,
    KEY_TOGGLE_QUIT,
    KEY_MODE_TERRAIN,
    KEY_MODE_AWAIT_TERRAIN,
    KEY_MODE_NAVIGATE,
    KEY_MODE_COMMAND,
    KEY_TOGGLE_DETAIL,
    KEY_TOGGLE_RETICULE,
    KEY_STEP_EE,
    KEY_STEP_NE,
    KEY_STEP_NW,
    KEY_STEP_WW,
    KEY_STEP_SW,
    KEY_STEP_SE,
    KEY_JUMP_EE,
    KEY_JUMP_NE,
    KEY_JUMP_NW,
    KEY_JUMP_WW,
    KEY_JUMP_SW,
    KEY_JUMP_SE,
    KEY_DRAG_EE,
    KEY_DRAG_NE,
    KEY_DRAG_NW,
    KEY_DRAG_WW,
    KEY_DRAG_SW,
    KEY_DRAG_SE,
    KEY_PAINT_UNKNOWN,
    KEY_PAINT_WATER,
    KEY_PAINT_MOUNTAINS,
    KEY_PAINT_HILLS,
    KEY_PAINT_PLAINS,
    KEY_PAINT_FOREST,
    KEY_PAINT_TUNDRA,
    KEY_PAINT_DESERT,
    KEY_PAINT_JUNGLE,
    KEY_PAINT_SWAMP
};


#endif 
